In [1]:
import pandas as pd

In [5]:
path='/content/employee_5000_records.xlsx'
df=pd.read_excel(path)

In [6]:
# display first 10 rows
df.head(10)

   Employee_ID    Name Department   Salary     City
0       1007.0   Sneha         IT  95948.0  Gurgaon
1       4461.0  Anjali         IT  64771.0    Delhi
2       4182.0   Priya      Sales  34566.0     Pune
3       2535.0   Pooja         HR  99885.0  Gurgaon
4       1373.0   Sneha    Finance  57515.0  Gurgaon
5       1031.0   Karan    Finance  72680.0   Mumbai
6       2179.0   Rohit         IT  62699.0   Mumbai
7       3275.0   Vikas      Sales  40258.0    Delhi
8       3822.0    Amit         HR  99556.0  Gurgaon
9       4726.0   Pooja         HR  60042.0  Gurgaon

In [7]:
# display last 10 rows
df.tail(10)

      Employee_ID    Name Department   Salary     City
4990       4635.0   Karan  Marketing  82059.0    Noida
4991         69.0   Vikas         IT  68010.0  Gurgaon
4992         77.0   Rahul         HR  90929.0   Mumbai
4993       3531.0   Rahul  Marketing  79809.0     Pune
4994       3217.0   Sneha    Finance  67964.0   Mumbai
4995        222.0   Priya    Finance  86283.0  Gurgaon
4996        480.0   Rahul         IT  79613.0   Mumbai
4997        170.0   Pooja  Marketing  33002.0   Mumbai
4998        506.0  Anjali         HR  32327.0    Delhi
4999       1305.0    Amit    Finance  92338.0    Noida

In [8]:
 #Summary of DataFrame (data types, nulls)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  4900 non-null   float64
 1   Name         4900 non-null   object
 2   Department   4900 non-null   object
 3   Salary       4900 non-null   float64
 4   City         4900 non-null   object
dtypes: float64(2), object(3)
memory usage: 195.4+ KB

In [9]:
 # Statistical summary
df.describe()

       Employee_ID        Salary
count  4900.000000   4900.000000
mean   2401.279592  59942.342653
std    1386.480831  23110.174327
min       1.000000  20010.000000
25%    1200.750000  39941.750000
50%    2399.500000  60162.000000
75%    3602.250000  80299.000000
max    4800.000000  99980.000000

In [10]:
# Get column names
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'City'], dtype='object')

In [11]:
# Find duplicate rows
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [12]:
# Remove duplicates
df.drop_duplicates()

      Employee_ID    Name Department   Salary     City
0          1007.0   Sneha         IT  95948.0  Gurgaon
1          4461.0  Anjali         IT  64771.0    Delhi
2          4182.0   Priya      Sales  34566.0     Pune
3          2535.0   Pooja         HR  99885.0  Gurgaon
4          1373.0   Sneha    Finance  57515.0  Gurgaon
...           ...     ...        ...      ...      ...
4995        222.0   Priya    Finance  86283.0  Gurgaon
4996        480.0   Rahul         IT  79613.0   Mumbai
4997        170.0   Pooja  Marketing  33002.0   Mumbai
4998        506.0  Anjali         HR  32327.0    Delhi
4999       1305.0    Amit    Finance  92338.0    Noida

[4801 rows x 5 columns]

In [13]:
# Detect missing values
df.isnull()

      Employee_ID   Name  Department  Salary   City
0           False  False       False   False  False
1           False  False       False   False  False
2           False  False       False   False  False
3           False  False       False   False  False
4           False  False       False   False  False
...           ...    ...         ...     ...    ...
4995        False  False       False   False  False
4996        False  False       False   False  False
4997        False  False       False   False  False
4998        False  False       False   False  False
4999        False  False       False   False  False

[5000 rows x 5 columns]

In [17]:
Usage with null check
df.isnull().sum()

Employee_ID    100
Name           100
Department     100
Salary         100
City           100
dtype: int64

In [34]:
#Remove missing values
df.dropna()

      Employee_ID    Name Department   Salary     City
0          1007.0   Sneha         IT  95948.0  Gurgaon
1          4461.0  Anjali         IT  64771.0    Delhi
2          4182.0   Priya      Sales  34566.0     Pune
3          2535.0   Pooja         HR  99885.0  Gurgaon
4          1373.0   Sneha    Finance  57515.0  Gurgaon
...           ...     ...        ...      ...      ...
4995        222.0   Priya    Finance  86283.0  Gurgaon
4996        480.0   Rahul         IT  79613.0   Mumbai
4997        170.0   Pooja  Marketing  33002.0   Mumbai
4998        506.0  Anjali         HR  32327.0    Delhi
4999       1305.0    Amit    Finance  92338.0    Noida

[5000 rows x 5 columns]